### ISSUE TITLE
Self-host jQuery and Popper

### ISSUE THREAD

**Issue by konklone** [zvenyach-llc/zvenyach.com#2]
It's good that you're using SRI, which prevents code injection:

```html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
```

But this still shares visitor information with code.jquery.com and cdnjs.cloudflare.com, and these files are trivially self-hostable. A `wget` for each and an update of the path inside the web app should fix this.

**Comment by vdavez** [comment]
Good call @konklone. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vdavez** [comment]
Closing! Thanks again @konklone!
